spring:
  datasource:
    url: jdbc:h2:mem:oncampus
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
api:
  endpoint:
    base-url: '/api/v1'
debug: true